apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-payment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/3-mnms/devops.git  
    targetRevision: main
    path: charts/api/charts/payment  
    helm:
      valueFiles:
        - ../values/api/payment/values.yaml  
        - ../values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: payment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true