apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    repoURL: https://github.com/3-mnms/devops.git
    targetRevision: develop
    path: charts/infra
    helm:
      valueFiles:
        - $values-repo/values/infra/values-prod.yaml
        - $values-repo/values/values-prod.yaml
  sources: 
    - repoURL: https://github.com/3-mnms/devops.git
      targetRevision: develop
      path: charts/infra
      helm:
        valueFiles:
          - $values-repo/values/infra/values-prod.yaml
          - $values-repo/values/values-prod.yaml
    - repoURL: https://github.com/3-mnms/gitops-repo.git 
      targetRevision: feature/MNMS-313
      ref: values-repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true7