kafka:
  replicaCount: 2
  kafkaGlobalClusterId: "pYdR4Xe6T9K7zTArYtR9XA"
  image:
    repository: bitnami/kafka
    tag: 3.6.0
    pullPolicy: IfNotPresent

  kraft:
    enabled: true
  

  persistence:
    enabled: true
    storageClass: "hostpath" 
    size: 10Gi 

  kraftPersistence: 
    enabled: true
    storageClass: "hostpath" 
    size: 1Gi 

  service:
    type: ClusterIP
    port: 9092 
    headlessPort: 9093 

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  
  ui:
    clusterName: 'my-kafka-cluster'
    enabled: true
    image:
      repository: provectuslabs/kafka-ui
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080



