apiPayment:
  replicaCount: 1

  image:
    registry: rookiesdogun
    repository: api-payment
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  database:
    host: api-payment-database-service
    port: 3306
    name: payment
    username: rookies
    password: rookies

apiPaymentDatabase:
  replicaCount: 1

  auth:
    rootPassword: "rookies"
    database: payment
    username: rookies
    password: rookies

  service:
    name: api-payment-database-service
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""