apiFestival:
  replicaCount: 1

  image:
    registry: rookiesdogun
    repository: api-festival
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  database:
    host: api-festival-database-service
    port: 3306
    name: festival
    username: rookies
    password: rookies

apiFestivalDatabase:
  replicaCount: 1

  auth:
    rootPassword: "rookies"
    database: festival
    username: rookies
    password: rookies

  service:
    name: api-festival-database-service
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""