apiFestival:
  replicaCount: 1
  image:
    registry: rookiesdogun
    repository: api-festival
    tag: v20250905081623
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  database:
    host: api-festival-database-service
    port: 3306
    name: festival
    username: rookies
    password: rookies
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
apiFestivalDatabase:
  replicaCount: 1
  auth:
    rootPassword: "rookies"
    database: festival
    username: rookies
    password: rookies
  service:
    name: api-festival-database-service
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "gp2"
apiFestivalAi:
  replicaCount: 1
  image:
    registry: rookiesdogun
    # 후에 api-festival-ai 로 변경 필요
    repository: tekcit-ai
    tag: v0.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8084
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
